services:
  picturas-api-gateway:
    build:
      context: .
      dockerfile: ./api_gateway/remote/Dockerfile
    container_name: picturas-api-gateway
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - picturas-users
    networks:
      - picturas-network
    volumes:
      - ./api_gateway/secrets:/secrets
      - ./api_gateway/remote/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  picturas-frontend:
    build:
      context: ./frontend
    container_name: picturas-frontend
    ports:
      - "4173:4173"
    networks:
      - picturas-network
    restart: always

  ## Users

  picturas-users:
    build:
      context: ./users
    container_name: picturas-users
    env_file: .env
    environment:
      - USERS_DATABASE_URL
      - USERS_SECRET_KEY_BASE
      - USERS_PORT
    ports:
      - "4001:4001"
    depends_on:
      picturas-users-db:
        condition: service_healthy
    networks:
      - picturas-network
    volumes:
      - picturas-users-secrets:/app/secrets
    restart: always

  picturas-users-db:
    image: postgres:15
    container_name: picturas-users-db
    env_file: .env
    environment:
      POSTGRES_USER: ${USERS_DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${USERS_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${USERS_DB_NAME:-users_prod}
      POSTGRES_HOST: ${USERS_DB_HOST:-localhost}
    networks:
      - picturas-network
    volumes:
      - picturas-users-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${USERS_DB_USERNAME:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  ## Projects

  picturas-projects:
    build:
      context: ./projects
    container_name: picturas-projects
    env_file: .env
    environment:
      - PROJECTS_DATABASE_URL
      - PROJECTS_SECRET_KEY_BASE
      - PROJECTS_PORT
    ports:
      - "4002:4002"
    depends_on:
      picturas-projects-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - picturas-network
    volumes:
      - picturas-images:/images
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4002/api/health"]
      start_period: 20s
      interval: 10s
    restart: always

  picturas-projects-db:
    image: postgres:15
    container_name: picturas-projects-db
    env_file: .env
    environment:
      POSTGRES_USER: ${PROJECTS_DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${PROJECTS_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${PROJECTS_DB_NAME:-projects_prod}
      POSTGRES_HOST: ${PROJECTS_DB_HOST:-localhost}
    networks:
      - picturas-network
    volumes:
      - picturas-projects-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PROJECTS_DB_USERNAME:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - picturas-network
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 30s
    restart: always

  ## Tools

  picturas-watermark-tool-ms:
    image: prcsousa/picturas-watermark-tool-ms:latest
    container_name: picturas-watermark-tool-ms
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO
    volumes:
      - picturas-images:/images
    networks:
      - picturas-network
    depends_on:
      picturas-projects:
        condition: service_healthy
    restart: always

  picturas-bg-removal-tool-ms:
    build: ./tools/picturas-bg-removal-tool-ms
    container_name: picturas-bg-removal-tool-ms
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO
    volumes:
      - picturas-images:/images
    networks:
      - picturas-network
    depends_on:
      picturas-projects:
        condition: service_healthy
    restart: always

  picturas-border-tool-ms:
    build: ./tools/picturas-border-tool-ms
    container_name: picturas-border-tool-ms
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO
    volumes:
      - picturas-images:/images
    networks:
      - picturas-network
    depends_on:
      picturas-projects:
        condition: service_healthy
    restart: always

  picturas-brightness-tool-ms:
    build: ./tools/picturas-brightness-tool-ms
    container_name: picturas-brightness-tool-ms
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO
    volumes:
      - picturas-images:/images
    networks:
      - picturas-network
    depends_on:
      picturas-projects:
        condition: service_healthy
    restart: always

  picturas-contrast-tool-ms:
    build: ./tools/picturas-contrast-tool-ms
    container_name: picturas-contrast-tool-ms
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO
    volumes:
      - picturas-images:/images
    networks:
      - picturas-network
    depends_on:
      picturas-projects:
        condition: service_healthy
    restart: always

  picturas-rotate-tool-ms:
    build: ./tools/picturas-rotate-tool-ms
    container_name: picturas-rotate-tool-ms
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO
    volumes:
      - picturas-images:/images
    networks:
      - picturas-network
    depends_on:
      picturas-projects:
        condition: service_healthy
    restart: always

  picturas-resize-tool-ms:
    build: ./tools/picturas-resize-tool-ms
    container_name: picturas-resize-tool-ms
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO
    volumes:
      - picturas-images:/images
    networks:
      - picturas-network
    depends_on:
      picturas-projects:
        condition: service_healthy
    restart: always

  picturas-crop-tool-ms:
    build: ./tools/picturas-crop-tool-ms
    container_name: picturas-crop-tool-ms
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO
    volumes:
      - picturas-images:/images
    networks:
      - picturas-network
    depends_on:
      picturas-projects:
        condition: service_healthy
    restart: always

  picturas-object-detection-tool-ms:
    build: ./tools/picturas-object-detection-tool-ms
    container_name: picturas-object-detection-tool-ms
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO
    volumes:
      - picturas-images:/images
    networks:
      - picturas-network
    depends_on:
      picturas-projects:
        condition: service_healthy
    restart: always

  picturas-blur-tool-ms:
    build: ./tools/picturas-blur-tool-ms
    container_name: picturas-blur-tool-ms
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO
    volumes:
      - picturas-images:/images
    networks:
      - picturas-network
    depends_on:
      picturas-projects:
        condition: service_healthy
    restart: always

  picturas-hue-tool-ms:
    build: ./tools/picturas-hue-tool-ms
    container_name: picturas-hue-tool-ms
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO
    volumes:
      - picturas-images:/images
    networks:
      - picturas-network
    depends_on:
      picturas-projects:
        condition: service_healthy
    restart: always

  picturas-invert-tool-ms:
    build: ./tools/picturas-invert-tool-ms
    container_name: picturas-invert-tool-ms
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO
    volumes:
      - picturas-images:/images
    networks:
      - picturas-network
    depends_on:
      picturas-projects:
        condition: service_healthy
    restart: always

  picturas-sharpen-tool-ms:
    build: ./tools/picturas-sharpen-tool-ms
    container_name: picturas-sharpen-tool-ms
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO
    volumes:
      - picturas-images:/images
    networks:
      - picturas-network
    depends_on:
      picturas-projects:
        condition: service_healthy
    restart: always

  picturas-saturation-tool-ms:
    build: ./tools/picturas-saturation-tool-ms
    container_name: picturas-saturation-tool-ms
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO
    volumes:
      - picturas-images:/images
    networks:
      - picturas-network
    depends_on:
      picturas-projects:
        condition: service_healthy
    restart: always

volumes:
  picturas-users-secrets:

  picturas-users-pgdata:
  picturas-projects-pgdata:

  picturas-images:

  rabbitmq-data:
  rabbitmq-log:

networks:
  picturas-network:
    driver: bridge
